server:
  port: 8080
spring:
  application:
    name: eureka-consumer # 应用名称
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 30

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
ribbon:
  eager-load:
    enabled: true
    clients: eureka-service
  ConnectTimeout: 500 # 连接超时时长
  ReadTimeout: 2000 # 数据通信超时时长
  MaxAutoRetries: 0 # 当前服务器的重试次数
  MaxAutoRetriesNextServer: 1 # 重试多少次服务
  OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试

feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true

logging:
  level:
    cn.itcast.consumer: debug